/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scenes` | `/scenes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/security/access-history`; params?: Router.UnknownInputParams; } | { pathname: `/security/alarm-controls`; params?: Router.UnknownInputParams; } | { pathname: `/security/live-camera`; params?: Router.UnknownInputParams; } | { pathname: `/security/notifications`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scenes` | `/scenes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/security/access-history`; params?: Router.UnknownOutputParams; } | { pathname: `/security/alarm-controls`; params?: Router.UnknownOutputParams; } | { pathname: `/security/live-camera`; params?: Router.UnknownOutputParams; } | { pathname: `/security/notifications`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scenes${`?${string}` | `#${string}` | ''}` | `/scenes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/security${`?${string}` | `#${string}` | ''}` | `/security${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/security/access-history${`?${string}` | `#${string}` | ''}` | `/security/alarm-controls${`?${string}` | `#${string}` | ''}` | `/security/live-camera${`?${string}` | `#${string}` | ''}` | `/security/notifications${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scenes` | `/scenes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/security` | `/security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/security/access-history`; params?: Router.UnknownInputParams; } | { pathname: `/security/alarm-controls`; params?: Router.UnknownInputParams; } | { pathname: `/security/live-camera`; params?: Router.UnknownInputParams; } | { pathname: `/security/notifications`; params?: Router.UnknownInputParams; };
    }
  }
}
